---
# main tasks file for wordpress role

# Variables ##########

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: set facts based on defaults
  set_fact:
    "{{ item[8:] }}": "{{  vars[item[8:]] | default(vars[item]) }}"
  when: item is match("^default_")
  with_items:
    "{{ vars }}"

# End Variables ##########

- name: update packages
  include_tasks: update_packages.yml
  when: run_update_packages is defined

- name: deploy users
  include_tasks: deploy_users.yml
  when: run_deploy_users is defined

- name: install webserver
  include_tasks: webserver.yml
  when: run_webserver is defined

- name: install shared files
  include_tasks: sharedfiles.yml
  when:
    - wordpress_create_shared
    - run_webserver is defined

- name: install email
  include_tasks: email.yml
  when: run_email is defined

- name: install mysql
  include_tasks: mysql.yml
  when: run_mysql is defined

- name: deploy wordpress code
  include_tasks: wpapp.yml
  when: run_wpapp is defined

- name: backup
  include_tasks: backup.yml
  when: run_backup is defined
