---
- name: apt update
  apt: update_cache=yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: install general packages (Debian)
  apt:
    name: "{{ wordpress_packages_general }}"
    state: present
  when: ansible_os_family == "Debian"

- name: install general packages (RHEL)
  yum:
    name: "{{ wordpress_packages_general }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: install python packages
  package:
    name: "{{ wordpress_python_packages }}"
    state: present

- name: install pip packages
  pip:
    name:
      - passlib
  changed_when: false
