---
- name: install apache
  include_tasks: apache.yml
  when: wordpress_webserver == "apache"

#for later
- name: install nginx
  include_tasks: nginx.yml
  static: no
  when: wordpress_webserver == "nginx"